services:
  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cooldatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: [ '--default-authentication-plugin=mysql_native_password', '--ssl=0' ]
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - backend

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cooldatabase
    ports:
      - "27017:27017"
    command: [ "--auth" ]
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cooldatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

volumes:
  mysql-data:
  mongo-data:
  postgres-data:

networks:
  backend:
