# WorldwideChat Configuration
#       _    _            _     _          _     _      _____ _           _   
#      | |  | |          | |   | |        (_)   | |    /  __ \ |         | |  
#      | |  | | ___  _ __| | __| |_      ___  __| | ___| /  \/ |__   __ _| |_ 
#      | |/\| |/ _ \| '__| |/ _` \ \ /\ / / |/ _` |/ _ \ |   | '_ \ / _` | __|    - by Dominic Feliton
#      \  /\  / (_) | |  | | (_| |\ V  V /| | (_| |  __/ \__/\ | | | (_| | |_ 
#       \/  \/ \___/|_|  |_|\__,_| \_/\_/ |_|\__,_|\___|\____/_| |_|\__,_|\__|
#
# HOW TO SETUP: https://github.com/dominicfeliton/WorldwideChat/wiki/Default-Explained-config.yml
#
General:
  prefixName: WWC
  enablebStats: true
  pluginLang: en
  updateCheckerDelay: 86400
  syncUserDataDelay: 7200
  fatalAsyncTaskTimeout: 10
  enableDebugMode: false
  syncUserLocalization: true
  enableSounds: true
Storage:
  useSQL: false
  sqlHostname: localhost
  sqlPort: 3306
  sqlDatabaseName: cooldatabase
  sqlUsername: root
  sqlPassword: root
  sqlUseSSL: false
  sqlOptionalArgs: [ ]
  useMongoDB: false
  mongoHostname: localhost
  mongoPort: 27017
  mongoDatabaseName: cooldatabase
  mongoUsername: admin
  mongoPassword: password
  mongoOptionalArgs: [ ]
  usePostgreSQL: false
  postgresHostname: localhost
  postgresPort: 5432
  postgresDatabaseName: cooldatabase
  postgresUsername: admin
  postgresPassword: password
  postgresSSL: false
  postgresOptionalArgs: [ ]
Chat:
  sendTranslationChat: true
  sendPluginUpdateChat: true
  sendIncomingHoverTextChat: true
  sendOutgoingHoverTextChat: true
  enableBlacklist: false
  useVault: true
  chatListenerPriority: HIGHEST
  separateChatChannel:
    icon: globe
    format: "{prefix}{username}{suffix}:"
    hoverFormat: "&o{local:wwcOrigHover}:"
    force: false
Translator:
  useAmazonTranslate: false
  amazonAccessKey: amazon_translate_key_goes_here
  amazonSecretKey: amazon_translate_secret_goes_here
  amazonRegion: amazon_region_goes_here
  useAzureTranslate: false
  azureAPIKey: azure_key_goes_here
  azureRegion: azure_region_goes_here
  useChatGPT: false
  chatGPTAPIKey: chatgpt_key_goes_here
  chatGPTModel: gpt-4o-2024-08-06
  chatGPTURL: "https://api.openai.com/v1/chat/completions"
  useDeepLTranslate: false
  deepLAPIKey: deepl_key_goes_here
  useGoogleTranslate: false
  googleTranslateAPIKey: google_translate_key_goes_here
  useLibreTranslate: false
  libreAPIKey: none
  libreURL: libre_url_goes_here
  useOllama: false
  ollamaURL: ollama_url_goes_here
  ollamaModel: finalend/hermes-3-llama-3.1:8b
  useSystranTranslate: false
  systranAPIKey: systran_key_goes_here
  translatorCacheSize: 100
  enablePersistentCache: false
  rateLimit: 0
  messageCharLimit: 255
  errorLimit: 5
  errorsToIgnore:
    - "confidence"
    - "same as target"
    - "detect the source language"
    - "Unable to find model for specified languages"
