name: WorldwideChat
version: 1.19.0
api-version: 1.13
description: Break the blocky language barrier!
author: Dominic Feliton
main: com.dominicfeliton.worldwidechat.WorldwideChat
folia-supported: false
softdepend: [Vault, PlaceholderAPI]
commands:
    wwc:
        description: Prints WorldwideChat version.
        aliases: [worldwidechat]
        usage: §4/wwc
        permission: worldwidechat.wwc
        permission-message: §4You do not have permission to run this command.
    wwcr:
        description: Reloads WorldwideChat.
        aliases: [wwcreload, translatereload]
        usage: §4/wwcr
        permission: worldwidechat.wwcr
        permission-message: §4You do not have permission to run this command.
    wwcd:
        description: Debug helper for WorldwideChat.
        aliases: [wwcdebug, translatedebug]
        usage: §4/wwcd (cache/checkdb/save/debugenv/reset) (args)
        permission: worldwidechat.wwcd
        permission-message: §4You do not have permission to run this command.
    wwcg:
        description: Enables chat translation to a certain language globally.
        aliases: [wwcglobal, gtranslate]
        usage: §4/wwcg (language-in) (language-out)
        permission: worldwidechat.wwcg
        permission-message: §4You do not have permission to run this command.
    wwct:
        description: Enables chat translation to a certain language, either for you or a specific player.
        aliases: [wwctranslate, translate]
        usage: §4/wwct (playerName) (language-in) (language-out)
        permission: worldwidechat.wwct
        permission-message: §4You do not have permission to run this command.
    wwctb:
        description: Enables book translation to a certain language.
        aliases: [wwctranslatebook, translatebook]
        usage: §4/wwctb (playerName)
        permission: worldwidechat.wwctb
        permission-message: §4You do not have permission to run this command.
    wwcts:
        description: Enables sign translation to a certain language.
        aliases: [wwctranslatesign, translatesign]
        usage: §4/wwcts (playerName)
        permission: worldwidechat.wwcts
        permission-message: §4You do not have permission to run this command.
    wwcti:
        description: Enables item translation to a certain language.
        aliases: [wwctranslateitem, translateitem]
        usage: §4/wwcti (playerName)
        permission: worldwidechat.wwcti
        permission-message: §4You do not have permission to run this command.
    wwcte:
        description: Enables entity translation to a certain language.
        aliases: [wwctranslateentity, translateentity]
        usage: §4/wwcte (playerName)
        permission: worldwidechat.wwcte
        permission-message: §4You do not have permission to run this command.
    wwctco:
        description: Enables outgoing chat translation to a certain language.
        aliases: [wwctranslatechatoutgoing, translatechatoutgoing]
        usage: §4/wwctco (playerName)
        permission: worldwidechat.wwctco
        permission-message: §4You do not have permission to run this command.
    wwctci:
        description: Enables incoming chat translation to a certain language.
        aliases: [wwctranslatechatincoming, translatechatincoming]
        usage: §4/wwctci (playerName)
        permission: worldwidechat.wwctci
        permission-message: §4You do not have permission to run this command.
    wwcs:
        description: Gets translation stats for a specified user.
        aliases: [wwctranslatestats, translatestats]
        usage: §4/wwcs (playerName)
        permission: worldwidechat.wwcs
        permission-message: §4You do not have permission to run this command.
    wwcc:
        description: Opens the Configuration GUI for the command sender.
        aliases: [wwcconfiguration, translateconfiguration]
        usage: §4/wwcc
        permission: worldwidechat.wwcc
        permission-message: §4You do not have permission to run this command.
    wwctrl:
        description: Sets a rate limit for the specified user.
        aliases: [wwctranslateratelimit, translateratelimit]
        usage: §4/wwctrl (delay) or /wwctrl (playerName) (delay)
        permission: worldwidechat.wwctrl
        permission-message: §4You do not have permission to run this command.
    wwcl:
        description: Sets a localization for a user.
        aliases: [wwclocalize, translatelocalize]
        usage: §4/wwcl (localization) or /wwcl (playerName) (localization)
permissions:
    worldwidechat.*:
        description: Gives access to all WorldwideChat commands.
        children:
            worldwidechat.wwc: true
            worldwidechat.wwcr: true
            worldwidechat.wwcd: true
            worldwidechat.wwcg: true
            worldwidechat.wwct: true
            worldwidechat.wwct.otherplayers: true
            worldwidechat.wwcl: true
            worldwidechat.wwcl.otherplayers: true
            worldwidechat.chatupdate: true
            worldwidechat.wwctb: true
            worldwidechat.wwctb.otherplayers: true
            worldwidechat.wwcts: true
            worldwidechat.wwcts.otherplayers: true
            worldwidechat.wwcti: true
            worldwidechat.wwcti.otherplayers: true
            worldwidechat.wwcte: true
            worldwidechat.wwcte.otherplayers: true
            worldwidechat.wwctco: true
            worldwidechat.wwctco.otherplayers: true
            worldwidechat.wwctci: true
            worldwidechat.wwctci.otherplayers: true
            worldwidechat.wwcs: true
            worldwidechat.wwcc: true
            worldwidechat.wwctrl: true
            worldwidechat.ratelimit.exempt: true
            worldwidechat.blacklist.exempt: true
        default: op
    worldwidechat.wwc:
        description: Gives access to /wwc.
        default: true
    worldwidechat.wwcr:
        description: Gives access to /wwcr.
        default: op
    worldwidechat.wwcd:
        description: Gives access to /wwcd.
        default: op
    worldwidechat.wwcg:
        description: Gives access to /wwcg.
        default: op
    worldwidechat.wwct:
        description: Gives access to /wwct.
        default: true
    worldwidechat.wwct.otherplayers:
        description: Gives access to /wwct on target players.
        default: op
    worldwidechat.chatupdate:
        description: Gives access to receiving of plugin update notification in chat on login.
        default: op
    worldwidechat.wwctb:
        description: Gives access to /wwctb.
        default: true
    worldwidechat.wwctb.otherplayers:
        description: Gives access to /wwctb on target players.
        default: op
    worldwidechat.wwcts:
        description: Gives access to /wwcts.
        default: true
    worldwidechat.wwcts.otherplayers:
        description: Gives access to /wwcts on target players.
        default: op
    worldwidechat.wwcti:
        description: Gives access to /wwcti.
        default: true
    worldwidechat.wwcti.otherplayers:
        description: Gives access to /wwcti on target players.
        default: op
    worldwidechat.wwcte:
        description: Gives access to /wwcte.
        default: true
    worldwidechat.wwcte.otherplayers:
        description: Gives access to /wwcte on target players.
        default: op
    worldwidechat.wwctco:
        description: Gives access to /wwctco.
        default: true
    worldwidechat.wwctco.otherplayers:
        description: Gives access to /wwctco on target players.
        default: op
    worldwidechat.wwctci:
        description: Gives access to /wwctci.
        default: true
    worldwidechat.wwctci.otherplayers:
        description: Gives access to /wwctci on target players.
        default: op
    worldwidechat.wwcs:
        description: Gives access to /wwcs.
        default: op
    worldwidechat.wwcc:
        description: Gives access to /wwcc.
        default: op
    worldwidechat.wwctrl:
        description: Gives access to /wwctrl.
        default: op
    worldwidechat.wwcl:
        description: Gives access to /wwcl.
        default: true
    worldwidechat.wwcl.otherplayers:
        description: Gives access to /wwcl on other players.
        default: op
    worldwidechat.ratelimit.exempt:
        description: Exempts a user from rate limits, both personally and globally.
        default: op
    worldwidechat.blacklist.exempt:
        description: Exempts a user from the blacklist.
        default: op
